name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run:  make build
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Scan image
        uses: anchore/scan-action@v6
        with:
          image: "microservices-kotlin-v2:latest"
          fail-build: false
          severity-cutoff: high
          output-format: table
          output-file: "scan-report.txt"

      - name: Show Reports
        run: |
          cat scan-report.txt
        shell: bash

      - name: Build and push
        run: make integrationTest
